### PR TITLE
!args -> !args[0]

### PR DESCRIPTION
**Pull request by rjm-codes**
should work, I'm pretty sure.

### CODE REVIEW

**Comment by whomhasfallen** [comment]
Hmm.

**Review by whomhasfallen — APPROVED** [review]
Well, there's no first, second, third, it's just saying what's provided after the "b:say" / "b:esay" parts. I approve.

**Comment by rjm-codes** [comment]
0 counts as the first argument, but yeah, I see what you mean.

**Comment by whomhasfallen** [comment]
Yep.

**Pull request merged**
